### ISSUE TITLE
Suggestion about player-blocking-damage-multiplier

### ISSUE THREAD

**Issue by MisterLolxd2** [arkflame/FlamePaper#49]
Hello again,

In paper.yml we have a "player-blocking-damage-multiplier: 0.5", but this option doesn't work because this variable is not included in the configuration (in classes). Would it be possible to fix this? I must admit that it would be nice to be able to edit the damage reduction as a result of holding the right mouse button.

**Comment by MisterLolxd2** [comment]
1 month later -_-

**Comment by MisterLolxd2** [comment]
Another month ;/

**Comment by linsaftw** [comment]
It will be taken in count :)

**Comment by iamnoksio** [comment]
> Another month ;/

There's something that's called DO IT YOURSELF

**Comment by MisterLolxd2** [comment]
I do not do it myself, because every update I would have to introduce it.And since I "supported" financially, I thought that this good creator would introduce it, because there is nothing to say, he is good.

**Comment by iamnoksio** [comment]
https://github.com/Weefle/ProtocolHack-1.9/blob/cd516a797bf624b71b84384b15de346efe2f526c/Spigot-Server-Patches/0008-Configurable-damage-multiplier-for-PvP-blocking.patch#L16

**Comment by iamnoksio** [comment]
go with PandaSpigot they are updating it much more

**Comment by linsaftw** [comment]
> I do not do it myself, because every update I would have to introduce it.And since I "supported" financially, I thought that this good creator would introduce it, because there is nothing to say, he is good.

I am working on many projects and dedicate my time to the most asked features first.
