### ISSUE TITLE
[ENHANCEMENT] Implement more patches

### ISSUE THREAD

**Issue by z2vvqx** [arkflame/FlamePaper#68]
There's so much patches not added in FlamePaper. It's a premium for after all, it should have all of the patches implemented in free forks. Such as **PandaSpigot**, **WindSpigot** and **etc**. More patches, more NEW features. Like PandaSpigot has 80+ patches and is free and has more new options than flamepaper. 

The problem is **PandaSpigot** is not made by professional like you @linsaftw, so it would be nice to see you the professional putting more effort in **FlamePaper** and implementing more **features**, **patches** and **creating new once**.

```List of patches from PandaSpigot:```
https://github.com/hpfxd/PandaSpigot/tree/master/patches/server

```List of patches from WindSpigot:```
https://github.com/Wind-Development/WindSpigot

Thank you. Good luck

**Comment by linsaftw** [comment]
Specify patches in separated issues. Otherwise this will be a never-ending issue. We already have many of those patches.
